### ISSUE TITLE
Unable to load reflection library

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [fbertola/Natrix#4]
Hello,
Thank you for sharing your code !
Unfortunatly I did managed to run it. I followed the poetry installation and trying to run the demo code got this:
```
raise RuntimeError("Unable to load reflection library "+name)
RuntimeError: Unable to load reflection library /home/.anaconda3//lib/python3.8/site-packages/pybgfx/libbgfx_pythonCppyy.so
```

Thank you for your help,
Best

**Comment by fbertola** [comment]
Hello @Thibaud-Ardoin. Unfortunately I'm not able to provide support for Anaconda but I would like you tu suggest with something smaller before tackling the whole demo project.
Given that there are many intermediate steps involved even for compiling the main library, try to run the examples first to familiarize yourselves with the code base.

Closing due to lack of information.
